"""
a2a_client.py
-------------
HTTP Client for Agent 1 (Quizmaster Agent).

Architecture & Role:
- Serves as the dispatching client in the Agent-to-Agent (A2A) protocol.
- Serializes student performance telemetry (A2APacket) into JSON format.
- Transmits telemetry to Agent 2 (Evaluator Server) via HTTP POST.
- Enforces timeout limits and catches network errors (connection refusal, timeouts).
- Receives and extracts the finalized ASCII report card and mentor feedback.
- Pairs with the server side implemented in evaluator/a2a_server.py.
"""

import sys
from dataclasses import asdict
import httpx

# ---------------------------------------------------------------------------
# Cross-Platform Console Encoding Setup
# ---------------------------------------------------------------------------
# Ensure standard output supports UTF-8 characters (useful for Windows terminals)
if hasattr(sys.stdout, "reconfigure"):
    getattr(sys.stdout, "reconfigure")(encoding="utf-8", errors="replace")

# Internal project imports: dataclass schema and evaluator server URL configuration
from core.models import A2APacket
from core.config import EVALUATOR_URL


# ===========================================================================
# Core A2A Client Transmission Logic
# ===========================================================================

def send_packet_to_evaluator(packet: A2APacket) -> str:
    """
    Serializes and transmits the A2APacket to the Evaluator server.
    
    Workflow:
    1. Converts the A2APacket dataclass into a JSON-serializable Python dictionary.
    2. Sends an HTTP POST request to the configured EVALUATOR_URL.
    3. Implements strict exception handling for connection errors and timeouts.
    4. Validates the HTTP 200 OK status code.
    5. Parses the JSON response and extracts the evaluated report card string.

    Parameters:
        packet (A2APacket): The completed quiz session telemetry data.

    Returns:
        str: The ASCII-formatted student performance report card generated by Agent 2.

    Raises:
        ConnectionError: If the Evaluator server is offline or unreachable.
        TimeoutError: If the server takes longer than the 20-second timeout window.
        RuntimeError: If the server returns a non-200 HTTP response.
    """
    # -----------------------------------------------------------------------
    # Step 1: Convert the dataclass object into a standard dictionary
    # -----------------------------------------------------------------------
    payload: dict = asdict(packet)

    # -----------------------------------------------------------------------
    # Step 2: Transmit HTTP POST request with network timeout guard
    # -----------------------------------------------------------------------
    try:
        response = httpx.post(
            EVALUATOR_URL,
            json=payload,
            timeout=20.0,  # 20-second timeout guard prevents hanging on slow networks
        )
    except httpx.ConnectError:
        # Raised when the server is not running or the port is blocked
        raise ConnectionError(
            f"Could not connect to the Evaluator server at {EVALUATOR_URL}.\n"
            "Make sure the evaluator server is running:\n"
            "  uv run python -m evaluator.a2a_server"
        )
    except httpx.TimeoutException:
        # Raised when the server accepted connection but took too long to evaluate
        raise TimeoutError(
            f"Evaluator server at {EVALUATOR_URL} timed out after 20 seconds."
        )

    # -----------------------------------------------------------------------
    # Step 3: Validate HTTP response status
    # -----------------------------------------------------------------------
    if response.status_code != 200:
        raise RuntimeError(
            f"Evaluator server returned an error: "
            f"{response.status_code} — {response.text}"
        )

    # -----------------------------------------------------------------------
    # Step 4: Parse response JSON and extract report card
    # -----------------------------------------------------------------------
    result: dict = response.json()
    return result.get("report_card", "No report card returned.")


# ===========================================================================
# Self-Contained Testing & Demonstration Entrypoint
# ===========================================================================

if __name__ == "__main__":
    """
    Standalone diagnostic script to verify client-to-server connectivity
    without needing to run through an entire interactive quiz session.
    """
    import uuid
    from datetime import datetime, timezone
    from core.models import PREREQUISITE_MAP

    print("=" * 60)
    print("  Testing A2A Client -> Server Connection")
    print(f"  Target Server: {EVALUATOR_URL}")
    print("=" * 60)

    # Construct a synthetic test packet with realistic telemetry data
    sample_packet = A2APacket(
        packet_id=str(uuid.uuid4()),
        timestamp=datetime.now(timezone.utc).isoformat(),
        student_name="Test Student",
        email="test@example.com",
        subject="Mathematics",
        topic_states={
            "Rational Numbers": {"status": "mastered", "correct_answers": 3, "questions_asked": 4},
            "Linear Equations": {"status": "weak", "correct_answers": 0, "questions_asked": 2},
        },
        question_history=[],
        weighted_scores={},
        total_correct=3,
        total_questions=6,
        prerequisite_map=PREREQUISITE_MAP,
    )

    # Attempt to transmit the synthetic test packet to the server
    try:
        print("[Client] Sending test packet to server...")
        report = send_packet_to_evaluator(sample_packet)
        print("\n[Success] Received evaluated report from server:")
        print("-" * 60)
        print(report)
    except ConnectionError as err:
        print(f"\n[Connection Error] {err}")
    except TimeoutError as err:
        print(f"\n[Timeout Error] {err}")
    except Exception as err:
        print(f"\n[Error] {err}")

